name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc         
    steps:
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable        
          override: true
          default: true
          target: ${{ matrix.target }}     
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check                    
      - name: Build
        working-directory: crates/c-api
        run: cargo build --target=${{ matrix.target }} --lib --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: 'target/${{ matrix.target }}/release/resvg.dll'
      - name: Build thumbnailer
        working-directory: tools/explorer-thumbnailer
        env:
          RUSTFLAGS: -Ctarget-feature=+crt-static # make sure it's static
        run: cargo build
